# config.yml

# Seulement utile pour python
commands: /configs/commands.xml

robots:
    spider:
        host: localhost # Adresse de connexion
        port: 12345 # Port (Si différent de 12345)
        environment: ../testconfigs/Spider/ # Emplacement de l'environement Spider
        loadMoves: [SpiderSinus]

    spider2:
        host: localhost # Adresse de connexion
        port: 12346 # Port (Si différent de 12345)
        environment: ../testconfigs/Spider/ # Emplacement de l'environement Spider
        loadMoves: [SpiderSinus]

    spider3:
        host: localhost # Adresse de connexion
        port: 12347 # Port (Si différent de 12345)
        environment: ../testconfigs/Spider/ # Emplacement de l'environement Spider
        loadMoves: [SpiderSinus]


