commands: ../../common/commands.xml
robots:
    django:
#       host: 192.168.16.24 # Adresse de connexion
        host: 127.0.0.1 # Adresse de connexion
        port: 7777 # Port (Si différent de 12345)
        environment: '/home/rhoban/Environments/RhobanServer'

